"use client";

import { collection, getDocs } from "firebase/firestore";
import { useEffect, useMemo, useState } from "react";
import { BarChart3, Users, ClipboardCheck, Activity, Trophy } from "lucide-react";
import AdminGuard from "@/components/AdminGuard";
import { db } from "@/lib/firebase/client";

type Attempt = { id: string; mockId?: string; userId?: string; score?: number; total?: number; status?: string; submittedAt?: { toDate?: () => Date } };
type Mock = { id: string; name?: string; questions?: number };
type Profile = { id: string; name?: string; displayName?: string; email?: string; lastLoginAt?: { toDate?: () => Date }; createdAt?: { toDate?: () => Date } };
const score = (a: Attempt) => Number(a.score || 0);
const nameOf = (profile?: Profile) => profile?.name || profile?.displayName || profile?.email || "Student";

function Analytics() {
  const [mocks, setMocks] = useState<Mock[]>([]); const [attempts, setAttempts] = useState<Attempt[]>([]); const [dailyAttempts, setDailyAttempts] = useState<Attempt[]>([]); const [profiles, setProfiles] = useState<Profile[]>([]); const [selected, setSelected] = useState<string | null>(null);
  useEffect(() => { Promise.all([getDocs(collection(db, "mocks")), getDocs(collection(db, "attempts")), getDocs(collection(db, "daily_attempts")), getDocs(collection(db, "profiles"))]).then(([m, a, d, p]) => { setMocks(m.docs.map(item => ({ id: item.id, ...item.data() }))); setAttempts(a.docs.map(item => ({ id: item.id, ...item.data() }))); setDailyAttempts(d.docs.map(item => ({ id: item.id, ...item.data() }))); setProfiles(p.docs.map(item => ({ id: item.id, ...item.data() }))); }).catch(console.error); }, []);
  const profileMap = useMemo(() => new Map(profiles.map(p => [p.id, p])), [profiles]);
  const rows = mocks.map(mock => { const list = attempts.filter(a => a.mockId === mock.id); const scores = list.map(score); const avg = scores.length ? scores.reduce((sum, value) => sum + value, 0) / scores.length : 0; const top = scores.length ? Math.max(...scores) : 0; return { mock, list, avg, top, percentile: mock.questions ? avg / (mock.questions * 3) * 100 : 0 }; });
  const selectedRow = rows.find(row => row.mock.id === selected);
  const today = new Date().toDateString(); const attemptedToday = attempts.filter(a => a.submittedAt?.toDate?.().toDateString() === today).length; const activeUsers = profiles.filter(profile => profile.lastLoginAt?.toDate?.().toDateString() === today).length; const recentRegistrations = profiles.filter(profile => profile.createdAt?.toDate?.().toDateString() === today).length;
  return <div className="mx-auto max-w-6xl px-4 py-12 sm:px-6 lg:px-8"><p className="text-xs font-semibold uppercase tracking-wide text-brand-dark">Admin</p><h1 className="mt-1 flex items-center gap-2 font-display text-[28px] font-bold"><BarChart3 className="text-brand" /> Performance & Analytics</h1><p className="mt-2 text-sm text-muted">Overview of engagement and all mock attempts. Select a test to view its rank list.</p>
    <div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={Activity} label="Today’s activity" value={`${attemptedToday} tests`} /><Metric icon={Users} label="Active users today" value={String(activeUsers)} /><Metric icon={ClipboardCheck} label="Tests attempted today" value={String(attemptedToday)} /><Metric icon={Trophy} label="New registrations today" value={String(recentRegistrations)} /></div>
    <section className="mt-8 rounded-2xl border border-border bg-white p-5"><h2 className="font-display text-lg font-semibold">Test performance</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[650px] text-left text-sm"><thead className="border-b border-border text-xs text-muted"><tr><th className="pb-3">Test</th><th className="pb-3">Attempts</th><th className="pb-3">Avg score</th><th className="pb-3">Avg %</th><th className="pb-3">Top score</th></tr></thead><tbody>{rows.map(row => <tr key={row.mock.id} onClick={() => setSelected(row.mock.id)} className="cursor-pointer border-b border-border last:border-0 hover:bg-brand-tint-2"><td className="py-3 font-semibold">{row.mock.name || "Untitled mock"}</td><td>{row.list.length}</td><td>{row.avg.toFixed(1)}</td><td>{row.percentile.toFixed(1)}%</td><td>{row.top}</td></tr>)}{rows.length === 0 && <tr><td colSpan={5} className="py-8 text-center text-muted">No mocks available yet.</td></tr>}</tbody></table></div></section>
    <section className="mt-6 rounded-2xl border border-border bg-white p-5"><h2 className="font-display text-lg font-semibold">Daily target performance</h2><div className="mt-4 grid gap-3 sm:grid-cols-3">{["quant", "varc", "dilr"].map(section => { const list = dailyAttempts.filter(attempt => (attempt as Attempt & { section?: string }).section === section); const scores = list.map(score); return <div key={section} className="rounded-xl bg-surface-muted p-4"><p className="font-semibold uppercase">{section}</p><p className="mt-2 text-sm text-muted">{list.length} attempts · Avg {scores.length ? (scores.reduce((sum, value) => sum + value, 0) / scores.length).toFixed(1) : "N/A"}</p><p className="mt-1 text-sm font-bold">Top {scores.length ? Math.max(...scores) : "N/A"}</p></div>; })}</div></section>
    {selectedRow && <section className="mt-6 rounded-2xl border border-brand/30 bg-white p-5"><h2 className="font-display text-lg font-semibold">{selectedRow.mock.name} — student performance</h2><p className="mt-1 text-sm text-muted">Highest score first; equal scores are listed alphabetically.</p><div className="mt-4 divide-y divide-border">{selectedRow.list.sort((a,b) => score(b) - score(a) || nameOf(profileMap.get(a.userId || "")).localeCompare(nameOf(profileMap.get(b.userId || "")))).map((attempt, index) => <div key={attempt.id} className="flex items-center justify-between py-3"><div><span className="mr-3 text-sm font-bold text-brand-darker">#{index + 1}</span><span className="font-medium">{nameOf(profileMap.get(attempt.userId || ""))}</span></div><span className="font-display font-bold">{score(attempt)}/{Number(attempt.total || selectedRow.mock.questions || 0) * 3}</span></div>)}{selectedRow.list.length === 0 && <p className="py-5 text-sm text-muted">No one has attempted this mock yet.</p>}</div></section>}
    <section className="mt-6 rounded-2xl border border-border bg-surface-muted p-5"><h2 className="font-display text-lg font-semibold">System alerts</h2><p className="mt-2 text-sm text-muted">No system alerts at the moment. Revenue and subscription reporting can be added here later.</p></section>
  </div>;
}
function Metric({ icon: Icon, label, value }: { icon: typeof Activity; label: string; value: string }) { return <div className="rounded-2xl border border-border bg-white p-4"><Icon size={17} className="text-brand" /><p className="mt-3 font-display text-xl font-bold">{value}</p><p className="text-xs text-muted">{label}</p></div>; }
export default function AdminAnalyticsPage() { return <AdminGuard><Analytics /></AdminGuard>; }
